name: Build LaTeX Document

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v4.1.1
    - name: Cache TeX Live installation
      uses: actions/cache@v4
      with:
        path: |
          /usr/local/texlive
        key: texlive-${runner.os}-${hashFiles('**/*.tex')}
    - name: Install TeX Live
      run: |
        sudo apt-get update -qy
        sudo apt-get install -qy texlive-xetex
    - name: Create build directory
      run: mkdir -p build
    - name: Build LaTeX document
      run: |
        cd $GITHUB_WORKSPACE/schaublin_13_first_gen/tex
        xelatex -interaction=nonstopmode -output-directory=$GITHUB_WORKSPACE/build main.tex
    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4.3.0
      with:
        name: output
        path: /home/runner/work/schaublin-13-manual/schaublin-13-manual/build/main.pdf
