name: Build LaTeX Document

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Install TeX Live
      run: |
        sudo apt-get update -qy
        sudo apt-get install -qy texlive-xetex
    - name: Create build directory
      run: mkdir -p build
    - name: Build LaTeX document
      run: |
        cd $GITHUB_WORKSPACE/schaublin_13_first_gen/tex
        xelatex -interaction=nonstopmode -output-directory=$GITHUB_WORKSPACE/build schaublin_13_first_gen/tex/main.tex
    - name: Upload PDF artifact
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: $GITHUB_WORKSPACE/build/main.pdf
